name: Build JohoBlue

on:
  push:
    branches:
      - main
  # Allows manual triggering from the website
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Needed to push to GHCR
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Using Buildah because it handles metadata better than Docker
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: johoblue
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile

      # Authenticate with GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push the image to your registry
      - name: Push Image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}